# Generated by Django 4.1.7 on 2023-03-15 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='item_image',
            new_name='item_image1',
        ),
        migrations.AddField(
            model_name='item',
            name='item_image2',
            field=models.ImageField(default='abc.jpg', upload_to='images'),
        ),
        migrations.AddField(
            model_name='item',
            name='item_image3',
            field=models.ImageField(default='abc.jpg', upload_to='images'),
        ),
    ]
