# Generated by Django 4.1.7 on 2023-04-03 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0003_rename_item_shape_item_item_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_no', models.CharField(max_length=5)),
                ('cvv', models.CharField(max_length=5)),
                ('expiry', models.CharField(max_length=10)),
                ('balance', models.FloatField(default=10000)),
            ],
            options={
                'db_table': 'payment',
            },
        ),
    ]
