# Generated by Django 4.1.7 on 2023-04-08 07:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0003_mycart'),
    ]

    operations = [
        migrations.CreateModel(
            name='orderMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_order', models.DateField(default=datetime.datetime.now)),
                ('amount', models.FloatField(default=1000)),
                ('details', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userApp.userinfo')),
            ],
            options={
                'db_table': 'orderMaster',
            },
        ),
    ]
